version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword


  server:
     build:
      context: ./server
      dockerfile: Dockerfile
     container_name: server
    
     ports:
      - 8761:8761

  activity-service:
     build:
      context: ./activity-service
      dockerfile: Dockerfile
     container_name: activity-service
    
     ports:
      - 8082:8082




