server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://127.0.0.1/fitness_userservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}