server:
  port: 8081

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:mysql://127.0.0.1/fitness_userservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
